all:
  hosts:
    127.0.0.1
  children:
    servers:
      children:
        k8s:
          children:
            master:
              hosts:
                192.168.0.105:
                  ansible_user: pi
        media_center:
          hosts:
            192.168.0.105:
              ansible_user: pi