- name: Install media center
  hosts: clusters
  remote_user: pi
  become: yes
  vars:
    kubernetes_version: 1.23.1
    container_runtime: containerd

  tasks:
  - name: Update system
    apt:
      update_cache: yes

  - name: Update packages
    apt:
      name: "*"
      state: latest

  - name: Installing packages
    apt:
      pkg:
        - kodi