- name: Update system
  become: yes
  apt:
    update_cache: yes

- name: Update packages
  become: yes
  apt:
    name: "*"
    state: latest

- name: Installing packages
  become: yes
  apt:
    pkg:
      - tmux
      - vim
      - screen